Add china.ts
PixelPizza/Bot pull request #391
Opened 2023-03-31 16:58 UTC by Spit-fires

Added command /china
Closes #372

2023-03-31 17:29 UTC, JaronZ requested changes
Is it possible to make it so this command fits in with the other commands?

2023-04-01 06:25 UTC, Spit-fires commented
> Is it possible to make it so this command fits in with the other commands?

As in code or the enviroment of bot?
if the command does not fit in with bot i can make it an guild only command

2023-07-14 21:25 UTC, JaronZ commented
@Spit-fires Please rebase

2023-07-18 22:51 UTC, JaronZ commented
@Spit-fires Please rebase

2023-07-19 19:10 UTC, JaronZ requested changes

2023-07-19 19:10 UTC, JaronZ commented on src/commands/china.ts
> +import { CommandInteraction, MessageEmbed } from "discord.js";
We are now using discord.js v14 which means MessageEmbed is now EmbedBuilder.
You also need Colors for embed colors now.
Lastly CommandInteraction is now ChatInputCommandInteraction

```suggestion
import { ChatInputCommandInteraction, EmbedBuilder, Colors } from "discord.js";
```

2023-07-20 08:28 UTC, JaronZ approved these changes

2023-07-21 06:53 UTC, Spit-fires commented
> Could make it add the China Flag when the Commmand is sent

Can you elaborate?

2023-08-13 23:49 UTC, JaronZ commented
@Spit-fires please rebase

2023-08-14 17:41 UTC, Spit-fires commented
> @Spit-fires please rebase
done

2023-08-15 14:08 UTC, JaronZ commented
> > @Spit-fires please rebase
> > done

nice

2023-08-15 14:09 UTC, JaronZ commented
> > @Spit-fires please rebase
> > done

Also please be careful with unsigned commits. some of my branch protection does not allow merging PRs with unsigned commits

2023-10-21 21:33 UTC, JaronZ commented
@Spit-fires please don't forget to sign your commits

2023-10-22 08:33 UTC, merged